### ISSUE TITLE
specify dependencies (for pip)

### ISSUE THREAD

**Issue by videlec** [jdemeyer/pari_jupyter#7]
Doing
```
$ pip install pari_jupyter
```
would better install all dependencies (jupyter, jupyter_client, notebook, cython, ...).

**Comment by jdemeyer** [comment]
...but it won't be able to install the most important dependency, which is PARI. Anyway, this should be easy to fix. Bear with me, this is the first Python package that I created completely from scratch.

**Comment by jdemeyer** [comment]
Adding dependencies means that I need to use `setuptools` instead of `distutils`. I don't want to go there...

Anyway, Cython is not actually a dependency since I ship the `.c` files. I don't consider Jupyter to be a dependency: it's an addon for Jupyter, it doesn't really require Jupyter.

Closing as wontfix.

**Comment by jdemeyer** [comment]
Actually, `pip` is clever enough to recognize dependencies even if the `setup.py` file uses only `distutils`. That is great, so I can get the benefits of `pip` without the breakage from `setuptools`.

Regardless, I'll only add `ipykernel` as dependency since it is the only hard requirement.
